language: java
before_install:
  - chmod +x gradlew

addons:
  sonarcloud:
    organization: "mikesafonov-github"
install:
  - ./gradlew build test testIntegration pitest --scan
script:
  - sonar-scanner

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: releases
  api_key:  $GITHUB_OAUTH_TOKEN
  file: "./build/libs/jira-telegram-bot.jar"
  skip_cleanup: true
  draft: true
  on:
    tags: true

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/modules-2/
    - $HOME/.gradle/wrapper/dists/
    - ./.pitest/ # pitest history
