coverage:
  range: 70..100
  round: down
  precision: 2

comment:
  layout: "reach, diff, flags, files, footer"

ignore:
  - "src/main/kotlin/com/github/mikesafonov/jira/telegram/config/*"
  - "src/main/kotlin/com/github/mikesafonov/jira/telegram/dao/*"
  - "src/main/resources/*"